[package]
name = "Alignr"
version = "0.1.0"
authors = ["daniel.kohlsdorf <dkohlsdorf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound   = "*"
image   = "*"
rustfft = "*"
clap    = "2"
